# Generated by Django 5.1.1 on 2024-11-21 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livro', '0007_categoria_livros_categoria'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_user.user'),
            preserve_default=False,
        ),
    ]
